{
 "title": "openmetadata-sample-faker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_percent{instance=\"openmetadata-sample-faker:8080\", job=\"openmetadata-sample-faker\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "system_cpu_percent{instance=\"openmetadata-sample-faker:8080\", job=\"openmetadata-sample-faker\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_memory_percent{instance=\"openmetadata-sample-faker:8080\", job=\"openmetadata-sample-faker\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "process_memory_bytes{instance=\"openmetadata-sample-faker:8080\", job=\"openmetadata-sample-faker\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code!=\"307\"}[5m])) by (method, endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  increase(http_requests_total{status_code=~\"5..|4..\"}[$__range])\r\n) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}